global:
  scrape_interval: 15s
  scrape_timeout: 15s  # Increased from 10s to 15s

scrape_configs:
  - job_name: 'messaging_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['messaging_service:9091']  # Use service name instead of IP