global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'messaging_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.22.0.3:9091']  # ✅ Actual Container IP