global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'messaging_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.21.0.4:8080']  # ✅ Use container IP