global:
  scrape_interval: 15s
  scrape_timeout: 15s  # Increased from 10s to 15s

scrape_configs:
  - job_name: 'messaging_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.18.0.3:9091'] # Explicitly use the IP address