apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  SENDGRID_API_KEY: REFFQzY4MTItN0EzMS00MERFLTgzMkQtRDExNjdEMTVBNzdG
  SERVICE_PASSWORD: U0cuR0FsMTN5ZGhRMjZVSTlUNzhpZDRTZy54TDI3QmZxNlp0Y2VBWVNwVEV0MUVUWXlucnNScmgxNFlEMk92VUl4X2Nn
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
