name: CI/CD Pipeline for MessagingService

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering from GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the application with Maven (Skip Tests)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/messaging-service .
          docker tag ${{ secrets.DOCKER_USERNAME }}/messaging-service:latest ${{ secrets.DOCKER_USERNAME }}/messaging-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/messaging-service:latest

      # Step 7: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        run: |
          # Save the private key from GitHub Secrets
          printf "%s" "${{ secrets.EC2_KEY }}" > ~/decoded-key.pem
          chmod 400 ~/decoded-key.pem

          # SSH into EC2 instance
          ssh -o StrictHostKeyChecking=no -i ~/decoded-key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Stop and remove existing MessagingService container if running
            if [ "$(docker ps -aq -f name=messaging_service)" ]; then
              docker stop messaging_service
              docker rm messaging_service
            fi

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/messaging-service:latest

            # Run the MessagingService container
            docker run -d --name messaging_service -p 8080:8080 -p 9091:9091 \
              -e spring.security.user.password="${{ secrets.SERVICE_PASSWORD }}" \
              -e SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}" \
              -e spring.profiles.active=prod \
              --network messaging-network \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/messaging-service:latest

            # Restart Prometheus if needed
            if [ "$(docker ps -aq -f name=prometheus)" ]; then
              docker restart prometheus
            fi
          EOF